# Generated by Django 2.1.5 on 2020-03-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('project_id', models.CharField(max_length=2)),
                ('member1', models.CharField(max_length=9)),
                ('member2', models.CharField(max_length=9)),
                ('member3', models.CharField(max_length=9)),
                ('member4', models.CharField(max_length=9)),
                ('member5', models.CharField(max_length=9)),
            ],
        ),
    ]
