# Generated by Django 2.1.5 on 2020-03-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='team_name',
        ),
    ]
